name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Native image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-comparison: 'true'
          native-image-pr-comparison-parameter: 'analysis results, resource usage'

      - name: Build and run HelloWorld.java
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac HelloWorld.java
          native-image HelloWorld
          ./helloworld

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: nativeImage-${{ matrix.os }}
          path: helloworld*