name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Native image on ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game-of-life-native
    steps:
      - uses: actions/checkout@v4

      - uses: jessiscript/setup-graalvm@main
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-comparison: 'true'
          native-image-pr-comparison-parameter: 'analysis results, resource usage'

      - name: Get versions
        run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
            native-image --version

      - name: Build and run game of life
        run: mvn -Pnative package

      - name: Build native image
        run: native-image -cp target\game-of-life-1.0.0-SNAPSHOT.jar gameoflife.Main

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: nativeImage-ubuntu-latest
          path: gameoflife.Main